version: "3.7"

services:
  mongodb:
    image: mongo:latest
    stdin_open: true
    tty: true
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - /home/x/db:/data/db:rw
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root